// frontend/src/routes/(app)/projects/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { goto } from '$app/navigation'
  import { auth } from '$lib/stores/auth'
  import { notifications } from '$lib/stores/notifications'
  import { projectsApi, invitationsApi } from '$lib/services/api'
  import { ThemeToggle, ProfileMenu, Tooltip } from '$lib/components/ui'
  import InvitationsPanel from '$lib/components/InvitationsPanel.svelte'
  import PlaceholderPanel from '$lib/components/editor/PlaceholderPanel.svelte'
  import type { Project } from '$lib/types'
  import collabstLogo from '../../../assets/collabst-text-vertical.svg'
  import fileIcon from '../../../assets/collabst-file.svg'
  import Play from '@lucide/svelte/icons/play'
  import Trash2 from '@lucide/svelte/icons/trash-2'
  import UserPlus from '@lucide/svelte/icons/user-plus'
  import CircleHelp from '@lucide/svelte/icons/circle-help'
  import Rocket from '@lucide/svelte/icons/rocket'
  import Settings from '@lucide/svelte/icons/settings'

  let projects: Project[] = []
  let loading = true
  let mounted = false
  let showCreateModal = false
  let showInviteModal = false
  let showSettingsPanel = false
  let selectedProjectId: number | null = null
  let newProjectName = ''
  let newProjectDescription = ''
  let inviteEmail = ''
  let inviteRole = 'editor'

  // Helper to check if current user is a collaborator (not owner)
  function isCollaborator(project: Project): boolean {
    return project.current_user_role !== 'owner'
  }

  // Helper to get role badge color
  function getRoleBadgeClass(role: string): string {
    switch (role) {
      case 'admin': return 'role-admin'
      case 'editor': return 'role-editor'
      case 'reader': return 'role-reader'
      default: return 'role-owner'
    }
  }

  async function loadProjects() {
    try {
      projects = await projectsApi.list()
    } catch (error) {
      console.error('Failed to load projects:', error)
    } finally {
      loading = false
    }
  }

  async function handleCreateProject(e: Event) {
    e.preventDefault()
    try {
      await projectsApi.create(newProjectName, newProjectDescription)
      showCreateModal = false
      newProjectName = ''
      newProjectDescription = ''
      loadProjects()
      notifications.show('Project created successfully!', 'info', 2000)
    } catch (error: any) {
      console.error('Failed to create project:', error)
      const message = error?.response?.data?.detail || 'Failed to create project'
      notifications.show(message, 'error', 5000)
    }
  }

  async function handleDeleteProject(id: number) {
    if (!confirm('Are you sure you want to delete this project?')) return

    try {
      await projectsApi.delete(id)
      loadProjects()
      notifications.show('Project deleted successfully', 'info', 2000)
    } catch (error: any) {
      console.error('Failed to delete project:', error)
      const message = error?.response?.data?.detail || 'Failed to delete project'
      notifications.show(message, 'error', 5000)
    }
  }

  function handleOpenInviteModal(projectId: number) {
    selectedProjectId = projectId
    showInviteModal = true
  }

  async function handleSendInvite(e: Event) {
    e.preventDefault()
    if (!selectedProjectId) return

    try {
      await invitationsApi.send(selectedProjectId, inviteEmail, inviteRole)
      showInviteModal = false
      inviteEmail = ''
      inviteRole = 'editor'
      notifications.show('Invitation sent successfully!', 'info', 3000)
    } catch (error: any) {
      console.error('Failed to send invitation:', error)
      const message = error?.response?.data?.detail || 'Failed to send invitation'
      notifications.show(message, 'error', 5000)
    }
  }

  onMount(() => {
    loadProjects()
    // Set mounted immediately to prevent layout shift
    mounted = true
  })
</script>

<svelte:head>
  <title>Collabst</title>
</svelte:head>

{#if loading}
  <div class="loading">Loading projects...</div>
{:else}
  <div class="container" class:mounted={mounted}>
    <header>
      <div class="header-left">
      </div>
      <div class="header-right">
        <ThemeToggle />
        <ProfileMenu />
      </div>
    </header>

    <div class="main-container">
      <!-- Activity Bar -->
      <div class="activity-bar">
        <div class="spacer"></div>
        <div class="bottom-activities">
          <Tooltip text="Settings" position="right" delay={600}>
            <button
              class="activity-btn"
              class:active={showSettingsPanel}
              on:click={() => showSettingsPanel = !showSettingsPanel}
              aria-label="Settings"
            >
              <Settings size={24} />
            </button>
          </Tooltip>
          <Tooltip text="Typst Universe" position="right" delay={600}>
            <a
              class="activity-btn"
              href="https://typst.app/universe"
              target="_blank"
              rel="noopener noreferrer"
              aria-label="Typst Universe"
            >
              <Rocket size={24} />
            </a>
          </Tooltip>
          <Tooltip text="Help" position="right" delay={600}>
            <a
              class="activity-btn"
              href="https://typst.app/docs"
              target="_blank"
              rel="noopener noreferrer"
              aria-label="Help"
            >
              <CircleHelp size={24} />
            </a>
          </Tooltip>
          
          <div class="logo-container">
            <img src={collabstLogo} alt="collabst" class="collabst-logo" />
          </div>
        </div>
      </div>

      <!-- Settings Panel -->
      {#if showSettingsPanel}
        <PlaceholderPanel title="Settings" />
      {/if}

      <!-- Main Content -->
      <div class="content-wrapper">
        <div class="invitations-section">
          <InvitationsPanel />
        </div>

        <div class="content">
          <h1 class="page-title">Dashboard</h1>
          <button on:click={() => showCreateModal = true} class="create-btn">
            + New Project
          </button>

      <div class="projects-grid">
        {#if projects.length === 0}
          <div class="empty">
            <h2>No projects yet</h2>
            <p>Create your first project to get started!</p>
          </div>
        {:else}
          {#each projects as project (project.id)}
            <div class="project-card" on:click={() => goto(`/editor/${project.id}`)}>
              <div class="file-icon-container">
                <img src={fileIcon} alt="Project file" class="file-icon" />
                
                <div class="action-buttons">
                  <button
                    on:click|stopPropagation={() => goto(`/editor/${project.id}`)}
                    class="action-btn open-action"
                    title="Open"
                  >
                    <Play size={16} />
                    <span class="action-label">Open</span>
                  </button>
                  
                  {#if project.current_user_role === 'owner' || project.current_user_role === 'admin'}
                    <button
                      on:click|stopPropagation={() => handleOpenInviteModal(project.id)}
                      class="action-btn invite-action"
                      title="Invite"
                    >
                      <UserPlus size={16} />
                      <span class="action-label">Invite</span>
                    </button>
                  {/if}
                  
                  {#if project.current_user_role === 'owner'}
                    <button
                      on:click|stopPropagation={() => handleDeleteProject(project.id)}
                      class="action-btn delete-action"
                      title="Delete"
                    >
                      <Trash2 size={16} />
                      <span class="action-label">Delete</span>
                    </button>
                  {/if}
                </div>
              </div>

              <div class="project-info">
                <h3>{project.name}</h3>
                {#if project.current_user_role}
                  <span class="role-badge {getRoleBadgeClass(project.current_user_role)}">
                    {project.current_user_role}
                  </span>
                {/if}
              </div>
            </div>
          {/each}
        {/if}
      </div>
    </div>
      </div>
    </div>

    {#if showCreateModal}
      <div class="modal" on:click={() => showCreateModal = false}>
        <div class="modal-content" on:click|stopPropagation>
          <h2>Create New Project</h2>
          <form on:submit={handleCreateProject}>
            <div class="field">
              <label>Project Name</label>
              <input
                type="text"
                bind:value={newProjectName}
                required
                placeholder="My Awesome Project"
              />
            </div>
            <div class="field">
              <label>Description</label>
              <textarea
                bind:value={newProjectDescription}
                placeholder="A brief description of your project"
              />
            </div>
            <div class="modal-actions">
              <button type="button" on:click={() => showCreateModal = false} class="cancel-btn">
                Cancel
              </button>
              <button type="submit" class="submit-btn">
                Create Project
              </button>
            </div>
          </form>
        </div>
      </div>
    {/if}

    {#if showInviteModal}
      <div class="modal" on:click={() => showInviteModal = false}>
        <div class="modal-content" on:click|stopPropagation>
          <h2>Invite Collaborator</h2>
          <form on:submit={handleSendInvite}>
            <div class="field">
              <label>Email Address</label>
              <input
                type="email"
                bind:value={inviteEmail}
                required
                placeholder="collaborator@example.com"
              />
            </div>
            <div class="field">
              <label>Role</label>
              <select bind:value={inviteRole}>
                <option value="reader">Reader - Can only view</option>
                <option value="editor">Editor - Can edit files</option>
                <option value="admin">Admin - Can manage collaborators</option>
              </select>
            </div>
            <div class="modal-actions">
              <button type="button" on:click={() => showInviteModal = false} class="cancel-btn">
                Cancel
              </button>
              <button type="submit" class="submit-btn">
                Send Invitation
              </button>
            </div>
          </form>
        </div>
      </div>
    {/if}
  </div>
{/if}

<style>
  .container {
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    background: var(--bg-canvas, var(--bg-primary));
    visibility: hidden;
  }

  .container.mounted {
    visibility: visible;
    animation: fadeIn 0.1s ease-in;
  }

  @keyframes fadeIn {
    from {
      opacity: 0;
    }
    to {
      opacity: 1;
    }
  }

  .main-container {
    display: flex;
    flex: 1;
    overflow: hidden;
    background: var(--bg-top-bar);
    /* Prevent layout shift by reserving space for activity bar */
    min-height: 0;
  }

  .activity-bar {
    width: 56px;
    background: var(--bg-top-bar);
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    padding: var(--space-3) 0;
    flex-shrink: 0;
  }

  .spacer {
    flex: 1;
  }

  .bottom-activities {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: var(--space-2);
  }

  .activity-btn {
    width: 40px;
    height: 40px;
    display: flex;
    align-items: center;
    justify-content: center;
    background: transparent;
    border: none;
    border-radius: 6px;
    color: var(--text-secondary);
    cursor: pointer;
    transition: all 0.15s;
    text-decoration: none;
  }

  .activity-btn:hover {
    color: var(--text-primary);
    background: var(--surface-hover);
  }

  .activity-btn.active {
    color: var(--text-primary);
    background: var(--surface-hover);
  }

  .logo-container {
    width: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
    margin-top: var(--space-4);
    padding-bottom: var(--space-4);
  }

  .collabst-logo {
    width: auto;
    height: 110px;
    filter: brightness(0) saturate(100%) invert(60%) sepia(0%) saturate(0%) hue-rotate(0deg) brightness(95%) contrast(90%);
    pointer-events: none;
    user-select: none;
  }

  :global([data-theme="light"]) .collabst-logo {
    filter: brightness(0) saturate(100%) invert(40%) sepia(0%) saturate(0%) hue-rotate(0deg) brightness(90%) contrast(85%);
  }

  .content-wrapper {
    flex: 1;
    overflow-y: auto;
    display: flex;
    flex-direction: column;
    background: var(--bg-canvas, var(--bg-primary));
    border-top-left-radius: 8px;
    /* Prevent content jump during initial render */
    min-width: 0;
  }

  header {
    background: var(--bg-top-bar);
    padding: 0.4rem 1rem;
    display: flex;
    justify-content: space-between;
    align-items: center;
    color: var(--text-primary);
  }

  .header-left {
    display: flex;
    align-items: center;
    gap: 1rem;
  }

  .header-right {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    margin-left: auto;
  }

  .loading {
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 18px;
    color: var(--text-secondary);
    background: var(--bg-primary);
  }

  .invitations-section {
    padding: 2rem;
    padding-bottom: 1rem;
    flex-shrink: 0;
  }

  .content {
    padding: 2rem;
    padding-top: 1rem;
    flex: 1;
    /* Prevent initial flash */
    contain: layout style;
  }

  .page-title {
    font-size: 48px;
    font-weight: 700;
    margin: 0 0 2rem 0;
    color: var(--text-primary);
    text-align: left;
    font-family: 'DM Serif Display', Georgia, serif;
    letter-spacing: -0.02em;
  }

  .create-btn {
    background: var(--bg-canvas, var(--bg-primary));
    color: var(--text-primary);
    border: 2px solid var(--border-primary);
    padding: 0.75rem 1.5rem;
    border-radius: 4px;
    font-weight: 500;
    cursor: pointer;
    font-size: 14px;
    transition: all 0.2s;
    margin-bottom: 2rem;
  }

  .create-btn:hover {
    background: var(--surface-hover);
    border-color: var(--border-secondary);
  }

  .projects-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(160px, 1fr));
    gap: 2rem;
  }

  .empty {
    grid-column: 1 / -1;
    text-align: center;
    padding: 4rem;
    color: var(--text-secondary);
  }

  .empty h2 {
    color: var(--text-primary);
    font-weight: 600;
    margin-bottom: 0.5rem;
  }

  .project-card {
    display: flex;
    flex-direction: column;
    align-items: center;
    cursor: pointer;
    transition: transform 0.2s;
  }

  .project-card:hover {
    transform: translateY(-4px);
  }

  .file-icon-container {
    position: relative;
    width: 120px;
    height: 140px;
    display: flex;
    align-items: center;
    justify-content: center;
    margin-bottom: 0.75rem;
  }

  .file-icon {
    width: 100%;
    height: 100%;
    object-fit: contain;
    filter: drop-shadow(0 2px 8px rgba(0, 0, 0, 0.2));
  }

  .action-buttons {
    position: absolute;
    top: 65%;
    left: 50%;
    transform: translate(-50%, 0);
    display: flex;
    gap: 0.5rem;
    opacity: 0;
    transition: opacity 0.2s;
    pointer-events: none;
  }

  .file-icon-container:hover .action-buttons {
    opacity: 1;
    pointer-events: auto;
  }

  .action-btn {
    background: var(--bg-secondary);
    border: 1px solid var(--border-primary);
    color: var(--text-primary);
    padding: 0.5rem;
    border-radius: 4px;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: all 0.2s;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.3);
    position: relative;
  }

  .action-btn .action-label {
    position: absolute;
    top: -2rem;
    left: 50%;
    transform: translateX(-50%);
    background: var(--bg-secondary);
    border: 1px solid var(--border-primary);
    padding: 0.25rem 0.5rem;
    border-radius: 4px;
    font-size: 12px;
    white-space: nowrap;
    opacity: 0;
    pointer-events: none;
    transition: opacity 0.2s;
    box-shadow: 0 2px 8px rgba(0, 0, 0, 0.3);
  }

  .action-btn:hover .action-label {
    opacity: 1;
  }

  .action-btn:hover {
    background: var(--surface-hover);
    transform: scale(1.1);
  }

  .open-action:hover {
    border-color: var(--color-primary);
    color: var(--color-primary);
  }

  .invite-action:hover {
    border-color: #81c784;
    color: #81c784;
  }

  /* Light theme: darker green for better contrast */
  :global([data-theme="light"]) .invite-action:hover {
    border-color: #4caf50;
    color: #4caf50;
  }

  .delete-action:hover {
    border-color: #e57373;
    color: #e57373;
  }

  /* Light theme: darker red for better contrast */
  :global([data-theme="light"]) .delete-action:hover {
    border-color: #d32f2f;
    color: #d32f2f;
  }

  .project-info {
    text-align: center;
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.5rem;
    width: 100%;
  }

  .project-card h3 {
    font-size: 14px;
    font-weight: 500;
    color: var(--text-primary);
    margin: 0;
    word-break: break-word;
    max-width: 100%;
  }

  .role-badge {
    font-size: 10px;
    font-weight: 600;
    padding: 0.25rem 0.5rem;
    border-radius: 12px;
    text-transform: uppercase;
    letter-spacing: 0.5px;
  }

  .role-owner {
    background: rgba(14, 99, 156, 0.3);
    color: #4fc3f7;
    border: 1px solid rgba(79, 195, 247, 0.3);
  }

  /* Light theme: darker blue for better contrast */
  :global([data-theme="light"]) .role-owner {
    background: rgba(14, 99, 156, 0.15);
    color: #0d47a1;
    border: 1px solid rgba(13, 71, 161, 0.3);
  }

  .role-admin {
    background: rgba(156, 39, 176, 0.3);
    color: #ba68c8;
    border: 1px solid rgba(186, 104, 200, 0.3);
  }

  .role-editor {
    background: rgba(76, 175, 80, 0.3);
    color: #81c784;
    border: 1px solid rgba(129, 199, 132, 0.3);
  }

  .role-reader {
    background: rgba(158, 158, 158, 0.3);
    color: #bdbdbd;
    border: 1px solid rgba(189, 189, 189, 0.3);
  }

  .modal {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: rgba(0, 0, 0, 0.7);
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 2rem;
    z-index: 100;
  }

  .modal-content {
    background: var(--bg-secondary);
    padding: 2rem;
    border-radius: 6px;
    border: 1px solid var(--border-primary);
    width: 100%;
    max-width: 500px;
    box-shadow: 0 8px 32px rgba(0, 0, 0, 0.5);
  }

  .modal-content h2 {
    font-size: 20px;
    font-weight: 600;
    margin: 0 0 1.5rem 0;
    color: var(--text-primary);
  }

  .field {
    margin-bottom: 1rem;
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }

  label {
    font-size: 13px;
    font-weight: 500;
    color: var(--text-primary);
  }

  input, textarea, select {
    padding: 0.75rem;
    border: 1px solid var(--border-primary);
    border-radius: 4px;
    font-size: 14px;
    background: var(--bg-input);
    color: var(--text-primary);
    transition: all 0.2s;
  }

  input:focus, textarea:focus, select:focus {
    outline: none;
    border-color: var(--color-primary);
    background: var(--bg-secondary);
  }

  input::placeholder, textarea::placeholder {
    color: var(--text-muted);
  }

  textarea {
    min-height: 80px;
    font-family: inherit;
    resize: vertical;
  }

  select option {
    background: var(--bg-secondary);
    color: var(--text-primary);
  }

  .modal-actions {
    display: flex;
    gap: 0.75rem;
    justify-content: flex-end;
    margin-top: 1.5rem;
  }

  .modal-actions {
    display: flex;
    gap: 0.75rem;
    margin-top: 1.5rem;
  }

  .cancel-btn {
    flex: 1;
    background: transparent;
    color: var(--text-primary);
    border: 1px solid var(--border-primary);
    padding: 0.75rem;
    border-radius: 4px;
    font-weight: 500;
    cursor: pointer;
    font-size: 14px;
    transition: all 0.2s;
  }

  .cancel-btn:hover {
    background: var(--surface-hover);
    border-color: var(--border-secondary);
  }

  .submit-btn {
    flex: 1;
    background: var(--color-primary);
    color: white;
    border: 1px solid var(--color-primary-hover);
    padding: 0.75rem;
    border-radius: 4px;
    font-weight: 500;
    cursor: pointer;
    font-size: 14px;
    transition: all 0.2s;
  }

  .submit-btn:hover {
    background: var(--color-primary-hover);
  }
</style>

// frontend_dev/src/pages/Projects.tsx
import React, { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { projectsApi, invitationsApi } from '../services/api'
import { InvitationsPanel } from '../components/InvitationsPanel'
import type { Project } from '../types'

export const Projects: React.FC = () => {
  const [projects, setProjects] = useState<Project[]>([])
  const [loading, setLoading] = useState(true)
  const [showCreateModal, setShowCreateModal] = useState(false)
  const [showInviteModal, setShowInviteModal] = useState(false)
  const [selectedProjectId, setSelectedProjectId] = useState<number | null>(null)
  const [newProjectName, setNewProjectName] = useState('')
  const [newProjectDescription, setNewProjectDescription] = useState('')
  const [inviteEmail, setInviteEmail] = useState('')
  const [inviteRole, setInviteRole] = useState('editor')
  const { logout } = useAuth()
  const navigate = useNavigate()

  useEffect(() => {
    loadProjects()
  }, [])

  const loadProjects = async () => {
    try {
      const data = await projectsApi.list()
      setProjects(data)
    } catch (error) {
      console.error('Failed to load projects:', error)
    } finally {
      setLoading(false)
    }
  }

  const handleCreateProject = async (e: React.FormEvent) => {
    e.preventDefault()
    try {
      await projectsApi.create(newProjectName, newProjectDescription)
      setShowCreateModal(false)
      setNewProjectName('')
      setNewProjectDescription('')
      loadProjects()
    } catch (error) {
      console.error('Failed to create project:', error)
    }
  }

  const handleDeleteProject = async (id: number) => {
    if (!confirm('Are you sure you want to delete this project?')) return

    try {
      await projectsApi.delete(id)
      loadProjects()
    } catch (error) {
      console.error('Failed to delete project:', error)
    }
  }

  const handleOpenInviteModal = (projectId: number) => {
    setSelectedProjectId(projectId)
    setShowInviteModal(true)
  }

  const handleSendInvite = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!selectedProjectId) return

    try {
      await invitationsApi.send(selectedProjectId, inviteEmail, inviteRole)
      setShowInviteModal(false)
      setInviteEmail('')
      setInviteRole('editor')
      alert('Invitation sent successfully!')
    } catch (error: any) {
      console.error('Failed to send invitation:', error)
      alert(error.response?.data?.detail || 'Failed to send invitation')
    }
  }

  if (loading) {
    return <div style={styles.loading}>Loading projects...</div>
  }

  return (
    <div style={styles.container}>
      <header style={styles.header}>
        <h1 style={styles.title}>My Projects</h1>
        <div style={styles.headerActions}>
          <button onClick={() => setShowCreateModal(true)} style={styles.createButton}>
            + New Project
          </button>
          <button onClick={logout} style={styles.logoutButton}>
            Logout
          </button>
        </div>
      </header>

      <div style={{ padding: '2rem', paddingBottom: '1rem' }}>
        <InvitationsPanel />
      </div>

      <div style={styles.projectsGrid}>
        {projects.length === 0 ? (
          <div style={styles.empty}>
            <h2>No projects yet</h2>
            <p>Create your first project to get started!</p>
          </div>
        ) : (
          projects.map((project) => (
            <div key={project.id} style={styles.projectCard}>
              <h3 style={styles.projectName}>{project.name}</h3>
              <p style={styles.projectDescription}>
                {project.description || 'No description'}
              </p>
              <div style={styles.projectFooter}>
                <button
                  onClick={() => navigate(`/editor/${project.id}`)}
                  style={styles.openButton}
                >
                  Open
                </button>
                <button
                  onClick={() => handleOpenInviteModal(project.id)}
                  style={styles.inviteButton}
                >
                  👥 Invite
                </button>
                <button
                  onClick={() => handleDeleteProject(project.id)}
                  style={styles.deleteButton}
                >
                  Delete
                </button>
              </div>
            </div>
          ))
        )}
      </div>

      {showCreateModal && (
        <div style={styles.modal}>
          <div style={styles.modalContent}>
            <h2 style={styles.modalTitle}>Create New Project</h2>
            <form onSubmit={handleCreateProject}>
              <div style={styles.field}>
                <label style={styles.label}>Project Name</label>
                <input
                  type="text"
                  value={newProjectName}
                  onChange={(e) => setNewProjectName(e.target.value)}
                  required
                  style={styles.input}
                  placeholder="My Awesome Project"
                />
              </div>
              <div style={styles.field}>
                <label style={styles.label}>Description</label>
                <textarea
                  value={newProjectDescription}
                  onChange={(e) => setNewProjectDescription(e.target.value)}
                  style={{ ...styles.input, minHeight: '80px' }}
                  placeholder="A brief description of your project"
                />
              </div>
              <div style={styles.modalActions}>
                <button type="button" onClick={() => setShowCreateModal(false)} style={styles.cancelButton}>
                  Cancel
                </button>
                <button type="submit" style={styles.submitButton}>
                  Create Project
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {showInviteModal && (
        <div style={styles.modal}>
          <div style={styles.modalContent}>
            <h2 style={styles.modalTitle}>Invite Collaborator</h2>
            <form onSubmit={handleSendInvite}>
              <div style={styles.field}>
                <label style={styles.label}>Email Address</label>
                <input
                  type="email"
                  value={inviteEmail}
                  onChange={(e) => setInviteEmail(e.target.value)}
                  required
                  style={styles.input}
                  placeholder="collaborator@example.com"
                />
              </div>
              <div style={styles.field}>
                <label style={styles.label}>Role</label>
                <select
                  value={inviteRole}
                  onChange={(e) => setInviteRole(e.target.value)}
                  style={styles.input}
                >
                  <option value="reader">Reader - Can only view</option>
                  <option value="editor">Editor - Can edit files</option>
                  <option value="admin">Admin - Can manage collaborators</option>
                </select>
              </div>
              <div style={styles.modalActions}>
                <button type="button" onClick={() => setShowInviteModal(false)} style={styles.cancelButton}>
                  Cancel
                </button>
                <button type="submit" style={styles.submitButton}>
                  Send Invitation
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  )
}

const styles = {
  container: {
    minHeight: '100vh',
    background: '#f7fafc',
  },
  header: {
    background: 'white',
    padding: '1.5rem 2rem',
    borderBottom: '1px solid #e5e7eb',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  title: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#333',
  },
  headerActions: {
    display: 'flex',
    gap: '1rem',
  },
  createButton: {
    background: '#667eea',
    color: 'white',
    border: 'none',
    padding: '0.75rem 1.5rem',
    borderRadius: '6px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  logoutButton: {
    background: '#ef4444',
    color: 'white',
    border: 'none',
    padding: '0.75rem 1.5rem',
    borderRadius: '6px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  loading: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '18px',
    color: '#666',
  },
  projectsGrid: {
    padding: '2rem',
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))',
    gap: '1.5rem',
  },
  empty: {
    gridColumn: '1 / -1',
    textAlign: 'center' as const,
    padding: '4rem',
    color: '#666',
  },
  projectCard: {
    background: 'white',
    padding: '1.5rem',
    borderRadius: '8px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '1rem',
  },
  projectName: {
    fontSize: '18px',
    fontWeight: '600',
    color: '#333',
  },
  projectDescription: {
    color: '#666',
    fontSize: '14px',
    flex: 1,
  },
  projectFooter: {
    display: 'flex',
    gap: '0.5rem',
  },
  openButton: {
    flex: 1,
    background: '#667eea',
    color: 'white',
    border: 'none',
    padding: '0.5rem',
    borderRadius: '6px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  inviteButton: {
    background: '#10b981',
    color: 'white',
    border: 'none',
    padding: '0.5rem 1rem',
    borderRadius: '6px',
    fontWeight: '600',
    cursor: 'pointer',
    fontSize: '14px',
  },
  deleteButton: {
    background: '#fee',
    color: '#c33',
    border: 'none',
    padding: '0.5rem 1rem',
    borderRadius: '6px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  modal: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0,0,0,0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '2rem',
  },
  modalContent: {
    background: 'white',
    padding: '2rem',
    borderRadius: '12px',
    width: '100%',
    maxWidth: '500px',
  },
  modalTitle: {
    fontSize: '24px',
    fontWeight: 'bold',
    marginBottom: '1.5rem',
    color: '#333',
  },
  field: {
    marginBottom: '1rem',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.5rem',
  },
  label: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#333',
  },
  input: {
    padding: '0.75rem',
    border: '2px solid #e5e7eb',
    borderRadius: '6px',
    fontSize: '14px',
  },
  modalActions: {
    display: 'flex',
    gap: '1rem',
    marginTop: '1.5rem',
  },
  cancelButton: {
    flex: 1,
    background: '#e5e7eb',
    color: '#333',
    border: 'none',
    padding: '0.75rem',
    borderRadius: '6px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  submitButton: {
    flex: 1,
    background: '#667eea',
    color: 'white',
    border: 'none',
    padding: '0.75rem',
    borderRadius: '6px',
    fontWeight: '600',
    cursor: 'pointer',
  },
}
